
[env]
term = "xterm-256color"

[font]
size = 16.0

normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold   = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

[window]
title = "Hadley's Terminal"

[colors]
draw_bold_text_with_bright_colors = true

[general]

live_config_reload = true
# In ~/.config/alacritty/alacritty.toml
#
import = [
    # "~/.config/alacritty/themes/themes/google.toml"
    # "~/.config/alacritty/themes/themes/nord.toml"
    "~/.config/alacritty/themes/themes/night_owl.toml"
    # "~/.config/alacritty/themes/themes/tokyo_night.toml"
    # "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
